// ⚠ AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Source of truth: the Google Sheet. Run `npm run sync` to regenerate.
import type { Stay, Leg, Activity, TimelineDay } from "./trip";

export const stays = [
  {
    "id": "lake-maggiore",
    "name": "Regina Palace Hotel",
    "location": {
      "name": "Regina Palace Hotel",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Regina Palace Hotel, Stresa",
      "photo": "/photos/lake-maggiore.jpg"
    },
    "checkIn": "Jul 23",
    "checkOut": "Jul 26",
    "nights": 3,
    "description": "Grand lakeside hotel in Stresa for a friend's wedding celebration.",
    "category": "hotel",
    "emoji": "🏛️"
  },
  {
    "id": "tuscany",
    "name": "Lupaia Hotel",
    "location": {
      "name": "Lupaia Hotel",
      "coords": [
        43.0667,
        11.7167
      ],
      "type": "stay",
      "placeQuery": "Lupaia, Torrita di Siena",
      "photo": "/photos/tuscany.jpg"
    },
    "checkIn": "Jul 26",
    "checkOut": "Jul 29",
    "nights": 3,
    "description": "Hilltop boutique hotel near Monticchiello in the Val d'Orcia.",
    "category": "villa",
    "emoji": "🌿"
  },
  {
    "id": "puglia",
    "name": "Masseria le Carrube",
    "location": {
      "name": "Masseria le Carrube",
      "coords": [
        40.7285,
        17.5888
      ],
      "type": "stay",
      "placeQuery": "Masseria Le Carrube, Ostuni"
    },
    "checkIn": "Jul 29",
    "checkOut": "Aug 2",
    "nights": 4,
    "description": "Whitewashed masseria estate near the white city of Ostuni.",
    "category": "masseria",
    "emoji": "🫒"
  },
  {
    "id": "su-gologone",
    "name": "Su Gologone Experience Hotel",
    "location": {
      "name": "Su Gologone Experience Hotel",
      "coords": [
        40.2728,
        9.4512
      ],
      "type": "stay",
      "placeQuery": "Art-filled experience hotel at the foot of the Supramonte, near Oliena. Anniversary stay."
    },
    "checkIn": "Aug 2",
    "checkOut": "Aug 4",
    "nights": 2,
    "description": "",
    "category": "hotel",
    "emoji": "🏔️"
  },
  {
    "id": "spiagge-san-pietro",
    "name": "Spiagge San Pietro",
    "location": {
      "name": "Spiagge San Pietro",
      "coords": [
        39.2789,
        9.5936
      ],
      "type": "stay",
      "placeQuery": "Relaxed beach resort on the southeast coast at Castiadas, near Costa Rei."
    },
    "checkIn": "Aug 4",
    "checkOut": "Aug 6",
    "nights": 2,
    "description": "",
    "category": "resort",
    "emoji": "🏖️"
  }
] as unknown as Stay[];

export const legs = [
  {
    "id": "leg1",
    "from": {
      "name": "New York JFK",
      "coords": [
        40.6413,
        -73.7781
      ],
      "type": "airport",
      "placeQuery": "John F. Kennedy International Airport, Queens, New York",
      "photo": "/photos/JFK.jpg"
    },
    "to": {
      "name": "Milan Malpensa",
      "coords": [
        45.6306,
        8.7281
      ],
      "type": "airport",
      "placeQuery": "Milan Malpensa Airport",
      "photo": "/photos/MXP.jpg"
    },
    "mode": "flight",
    "date": "Jul 21",
    "status": "booked",
    "departureTime": "22:20",
    "arrivalTime": "12:15+1",
    "confirmation": "DFMZN5 (Qantas · EK operated)",
    "carrier": "Emirates",
    "flightNumber": "EK206",
    "notes": "Nonstop Economy · Bags: 2 checked (23kg) + carry-on + personal item pp · 7h 55m"
  },
  {
    "id": "leg2",
    "from": {
      "name": "Milan Malpensa",
      "coords": [
        45.6306,
        8.7281
      ],
      "type": "airport",
      "placeQuery": "Milan Malpensa Airport",
      "photo": "/photos/MXP.jpg"
    },
    "to": {
      "name": "Stresa, Lake Maggiore",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Stresa, Verbano-Cusio-Ossola, Italy",
      "photo": "/photos/STRESA.jpg"
    },
    "mode": "train",
    "date": "Jul 23",
    "status": "pending",
    "departureTime": "afternoon",
    "price": "~$34 for 2",
    "notes": "Trenord regional (1 connection, 1h15-1h50) · ~1h 30m"
  },
  {
    "id": "leg3",
    "from": {
      "name": "Stresa, Lake Maggiore",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Stresa, Verbano-Cusio-Ossola, Italy",
      "photo": "/photos/STRESA.jpg"
    },
    "to": {
      "name": "Milano Centrale",
      "coords": [
        45.4851,
        9.2035
      ],
      "type": "station",
      "placeQuery": "Milano Centrale railway station",
      "photo": "/photos/MILANO_CENTRALE.jpg"
    },
    "mode": "train",
    "date": "Jul 26",
    "status": "pending",
    "departureTime": "morning",
    "price": "~$34 for 2",
    "notes": "Trenord regional (1 connection) · ~1h 30m"
  },
  {
    "id": "leg4",
    "from": {
      "name": "Milano Centrale",
      "coords": [
        45.4851,
        9.2035
      ],
      "type": "station",
      "placeQuery": "Milano Centrale railway station",
      "photo": "/photos/MILANO_CENTRALE.jpg"
    },
    "to": {
      "name": "Firenze SMN",
      "coords": [
        43.776,
        11.2457
      ],
      "type": "station",
      "placeQuery": "Firenze Santa Maria Novella railway station",
      "photo": "/photos/FIRENZE_SMN.jpg"
    },
    "mode": "train",
    "date": "Jul 26",
    "status": "booked",
    "departureTime": "11:40",
    "arrivalTime": "13:35",
    "confirmation": "CCDUHP",
    "carrier": "Italo",
    "flightNumber": "Train 9931",
    "price": "$155.58 for 2 (Dhrumi Amex)",
    "notes": "Prima Business Flex · 1h 55m"
  },
  {
    "id": "leg5",
    "from": {
      "name": "Firenze SMN",
      "coords": [
        43.776,
        11.2457
      ],
      "type": "station",
      "placeQuery": "Firenze Santa Maria Novella railway station",
      "photo": "/photos/FIRENZE_SMN.jpg"
    },
    "to": {
      "name": "Lupaia, Tuscany",
      "coords": [
        43.0667,
        11.7167
      ],
      "type": "stay",
      "placeQuery": "Lupaia, Torrita di Siena, Tuscany",
      "photo": "/photos/LUPAIA.jpg"
    },
    "mode": "car",
    "date": "Jul 26",
    "status": "booked",
    "confirmation": "Hertz L64746533C6 / AE Voucher 359733840",
    "carrier": "Rental Car",
    "price": "$389.63 (Dhrumi Amex)",
    "notes": "Jeep Avenger or similar, Automatic Compact (Hertz, 3 days, drop at FCO) · ~1h 30m"
  },
  {
    "id": "leg6",
    "from": {
      "name": "Rome Fiumicino",
      "coords": [
        41.7999,
        12.2462
      ],
      "type": "airport",
      "placeQuery": "Leonardo da Vinci–Fiumicino Airport",
      "photo": "/photos/FCO.jpg"
    },
    "to": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyła Airport",
      "photo": "/photos/BRI.jpg"
    },
    "mode": "flight",
    "date": "Jul 29",
    "status": "booked",
    "departureTime": "15:15",
    "arrivalTime": "16:20",
    "confirmation": "Z24DST",
    "carrier": "ITA Airways",
    "flightNumber": "AZ1607",
    "price": "EUR 174.10 for 2",
    "notes": "Nonstop Economy · Bags: 1 checked (23kg, booked) + carry-on (8kg) + personal item pp · 1h 05m"
  },
  {
    "id": "leg7",
    "from": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyła Airport",
      "photo": "/photos/BRI.jpg"
    },
    "to": {
      "name": "Ostuni, Puglia",
      "coords": [
        40.7285,
        17.5888
      ],
      "type": "stay",
      "placeQuery": "Ostuni, Puglia, Italy",
      "photo": "/photos/OSTUNI.jpg"
    },
    "mode": "car",
    "date": "Jul 29",
    "status": "booked",
    "departureTime": "4:30",
    "arrivalTime": "9:00+1",
    "confirmation": "Auto Europe US645058086",
    "carrier": "Rental Car",
    "price": "$220",
    "notes": "Fiat 600 or similar, Automatic Compact (Auto Europe, 4 days, drop at BRI) · 4 days"
  },
  {
    "id": "leg8",
    "from": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyła Airport",
      "photo": "/photos/BRI.jpg"
    },
    "to": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport"
    },
    "mode": "flight",
    "date": "Aug 2",
    "status": "booked",
    "departureTime": "8:15",
    "arrivalTime": "9:45",
    "confirmation": "TSCHHB",
    "carrier": "Ryanair",
    "flightNumber": "FR8726",
    "price": "Euro 278 for 2",
    "notes": "Nonstop Economy · Bags: 2×20kg checked (booked) + 1 under-seat bag 40×20×25cm pp; no cabin bag · 1h 30m"
  },
  {
    "id": "leg9",
    "from": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport"
    },
    "to": {
      "name": "Sardinia",
      "coords": [
        39.2238,
        9.1217
      ],
      "type": "stay",
      "placeQuery": "Sardinia, Italy"
    },
    "mode": "car",
    "date": "Aug 2",
    "status": "booked",
    "departureTime": "10:00",
    "arrivalTime": "10:00+1",
    "confirmation": "Auto Europe US228145669 / Avis 20221246US3",
    "carrier": "Rental Car",
    "price": "$330",
    "notes": "Nissan Juke or similar, Automatic Compact (Avis via Auto Europe, 4 days, drop at CAG) · 4 days"
  },
  {
    "id": "leg10",
    "from": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport"
    },
    "to": {
      "name": "Paris CDG",
      "coords": [
        49.0097,
        2.5479
      ],
      "type": "airport",
      "placeQuery": "Paris Charles de Gaulle Airport"
    },
    "mode": "flight",
    "date": "Aug 6",
    "status": "booked",
    "departureTime": "12:30",
    "arrivalTime": "14:45",
    "confirmation": "XDQETZ",
    "carrier": "Air France",
    "flightNumber": "AF1111",
    "price": "120,000 miles + $882.46",
    "notes": "Business · Bags: 2 checked (32kg) + carry-on pp · 2h 15m"
  },
  {
    "id": "leg11",
    "from": {
      "name": "Paris CDG",
      "coords": [
        49.0097,
        2.5479
      ],
      "type": "airport",
      "placeQuery": "Paris Charles de Gaulle Airport"
    },
    "to": {
      "name": "New York JFK",
      "coords": [
        40.6413,
        -73.7781
      ],
      "type": "airport",
      "placeQuery": "John F. Kennedy International Airport, Queens, New York",
      "photo": "/photos/JFK.jpg"
    },
    "mode": "flight",
    "date": "Aug 6",
    "status": "booked",
    "departureTime": "20:30",
    "arrivalTime": "22:40",
    "confirmation": "XDQETZ",
    "carrier": "Air France",
    "flightNumber": "AF0012",
    "price": "see leg above",
    "notes": "8h 10m"
  }
] as unknown as Leg[];

export const activities = [
  {
    "id": "borromean",
    "name": "Borromean Islands",
    "location": {
      "name": "Borromean Islands",
      "coords": [
        45.8992,
        8.5108
      ],
      "type": "stay",
      "placeQuery": "Isola Bella, Stresa, Lake Maggiore",
      "photo": "/photos/borromean.jpg"
    },
    "category": "attraction",
    "emoji": "🏝️",
    "date": "Jul 23–25",
    "notes": "Baroque palace gardens on the lake"
  },
  {
    "id": "pienza",
    "name": "Pienza",
    "location": {
      "name": "Pienza",
      "coords": [
        43.0764,
        11.6801
      ],
      "type": "stay",
      "placeQuery": "Pienza, Siena, Tuscany",
      "photo": "/photos/pienza.jpg"
    },
    "category": "attraction",
    "emoji": "🗺️",
    "date": "Jul 27",
    "notes": "Renaissance hilltop town, 15 min from Lupaia"
  },
  {
    "id": "ostuni-town",
    "name": "Ostuni Old Town",
    "location": {
      "name": "Ostuni Old Town",
      "coords": [
        40.7317,
        17.5851
      ],
      "type": "stay",
      "placeQuery": "Ostuni, Puglia, Italy",
      "photo": "/photos/ostuni-town.jpg"
    },
    "category": "attraction",
    "emoji": "🕌",
    "date": "Jul 30",
    "notes": "The white city — stunning at sunset"
  }
] as unknown as Activity[];

export const timeline = [
  {
    "date": "July 21",
    "dateShort": "Jul 21",
    "location": "Home",
    "emoji": "🏠",
    "legs": [
      {
        "id": "leg1",
        "from": {
          "name": "New York JFK",
          "coords": [
            40.6413,
            -73.7781
          ],
          "type": "airport",
          "placeQuery": "John F. Kennedy International Airport, Queens, New York",
          "photo": "/photos/JFK.jpg"
        },
        "to": {
          "name": "Milan Malpensa",
          "coords": [
            45.6306,
            8.7281
          ],
          "type": "airport",
          "placeQuery": "Milan Malpensa Airport",
          "photo": "/photos/MXP.jpg"
        },
        "mode": "flight",
        "date": "Jul 21",
        "status": "booked",
        "departureTime": "22:20",
        "arrivalTime": "12:15+1",
        "confirmation": "DFMZN5 (Qantas · EK operated)",
        "carrier": "Emirates",
        "flightNumber": "EK206",
        "notes": "Nonstop Economy · Bags: 2 checked (23kg) + carry-on + personal item pp · 7h 55m"
      }
    ],
    "activities": [],
    "notes": [
      "Depart JFK on Emirates EK206 (overnight flight)"
    ]
  },
  {
    "date": "July 22",
    "dateShort": "Jul 22",
    "location": "Milan",
    "emoji": "✈️",
    "legs": [],
    "activities": [],
    "notes": [
      "Dinner at 9:30 at La Gioia San Marco for 6 people (booked)",
      "Arrive Milan Malpensa (EK206 lands midday)"
    ]
  },
  {
    "date": "July 23–25",
    "dateShort": "Jul 23–25",
    "location": "Lake Maggiore",
    "emoji": "🏛️",
    "stay": {
      "id": "lake-maggiore",
      "name": "Regina Palace Hotel",
      "location": {
        "name": "Regina Palace Hotel",
        "coords": [
          45.8832,
          8.5355
        ],
        "type": "stay",
        "placeQuery": "Regina Palace Hotel, Stresa",
        "photo": "/photos/lake-maggiore.jpg"
      },
      "checkIn": "Jul 23",
      "checkOut": "Jul 26",
      "nights": 3,
      "description": "Grand lakeside hotel in Stresa for a friend's wedding celebration.",
      "category": "hotel",
      "emoji": "🏛️"
    },
    "legs": [
      {
        "id": "leg2",
        "from": {
          "name": "Milan Malpensa",
          "coords": [
            45.6306,
            8.7281
          ],
          "type": "airport",
          "placeQuery": "Milan Malpensa Airport",
          "photo": "/photos/MXP.jpg"
        },
        "to": {
          "name": "Stresa, Lake Maggiore",
          "coords": [
            45.8832,
            8.5355
          ],
          "type": "stay",
          "placeQuery": "Stresa, Verbano-Cusio-Ossola, Italy",
          "photo": "/photos/STRESA.jpg"
        },
        "mode": "train",
        "date": "Jul 23",
        "status": "pending",
        "departureTime": "afternoon",
        "price": "~$34 for 2",
        "notes": "Trenord regional (1 connection, 1h15-1h50) · ~1h 30m"
      }
    ],
    "activities": [
      {
        "id": "borromean",
        "name": "Borromean Islands",
        "location": {
          "name": "Borromean Islands",
          "coords": [
            45.8992,
            8.5108
          ],
          "type": "stay",
          "placeQuery": "Isola Bella, Stresa, Lake Maggiore",
          "photo": "/photos/borromean.jpg"
        },
        "category": "attraction",
        "emoji": "🏝️",
        "date": "Jul 23–25",
        "notes": "Baroque palace gardens on the lake"
      }
    ],
    "notes": [
      "Welcome Party 6pm-11pm at Sky Bar at Hotel La Palma",
      "Haldi 10 am-2pm Sangeet 6:30pm-11:30pm at 3 Viale Siemens",
      "Baraat and Milni Reception Grand Hotel Des Iles Borromees"
    ]
  },
  {
    "date": "July 26–28",
    "dateShort": "Jul 26–28",
    "location": "Tuscany",
    "emoji": "🌿",
    "stay": {
      "id": "tuscany",
      "name": "Lupaia Hotel",
      "location": {
        "name": "Lupaia Hotel",
        "coords": [
          43.0667,
          11.7167
        ],
        "type": "stay",
        "placeQuery": "Lupaia, Torrita di Siena",
        "photo": "/photos/tuscany.jpg"
      },
      "checkIn": "Jul 26",
      "checkOut": "Jul 29",
      "nights": 3,
      "description": "Hilltop boutique hotel near Monticchiello in the Val d'Orcia.",
      "category": "villa",
      "emoji": "🌿"
    },
    "legs": [
      {
        "id": "leg3",
        "from": {
          "name": "Stresa, Lake Maggiore",
          "coords": [
            45.8832,
            8.5355
          ],
          "type": "stay",
          "placeQuery": "Stresa, Verbano-Cusio-Ossola, Italy",
          "photo": "/photos/STRESA.jpg"
        },
        "to": {
          "name": "Milano Centrale",
          "coords": [
            45.4851,
            9.2035
          ],
          "type": "station",
          "placeQuery": "Milano Centrale railway station",
          "photo": "/photos/MILANO_CENTRALE.jpg"
        },
        "mode": "train",
        "date": "Jul 26",
        "status": "pending",
        "departureTime": "morning",
        "price": "~$34 for 2",
        "notes": "Trenord regional (1 connection) · ~1h 30m"
      },
      {
        "id": "leg4",
        "from": {
          "name": "Milano Centrale",
          "coords": [
            45.4851,
            9.2035
          ],
          "type": "station",
          "placeQuery": "Milano Centrale railway station",
          "photo": "/photos/MILANO_CENTRALE.jpg"
        },
        "to": {
          "name": "Firenze SMN",
          "coords": [
            43.776,
            11.2457
          ],
          "type": "station",
          "placeQuery": "Firenze Santa Maria Novella railway station",
          "photo": "/photos/FIRENZE_SMN.jpg"
        },
        "mode": "train",
        "date": "Jul 26",
        "status": "booked",
        "departureTime": "11:40",
        "arrivalTime": "13:35",
        "confirmation": "CCDUHP",
        "carrier": "Italo",
        "flightNumber": "Train 9931",
        "price": "$155.58 for 2 (Dhrumi Amex)",
        "notes": "Prima Business Flex · 1h 55m"
      },
      {
        "id": "leg5",
        "from": {
          "name": "Firenze SMN",
          "coords": [
            43.776,
            11.2457
          ],
          "type": "station",
          "placeQuery": "Firenze Santa Maria Novella railway station",
          "photo": "/photos/FIRENZE_SMN.jpg"
        },
        "to": {
          "name": "Lupaia, Tuscany",
          "coords": [
            43.0667,
            11.7167
          ],
          "type": "stay",
          "placeQuery": "Lupaia, Torrita di Siena, Tuscany",
          "photo": "/photos/LUPAIA.jpg"
        },
        "mode": "car",
        "date": "Jul 26",
        "status": "booked",
        "confirmation": "Hertz L64746533C6 / AE Voucher 359733840",
        "carrier": "Rental Car",
        "price": "$389.63 (Dhrumi Amex)",
        "notes": "Jeep Avenger or similar, Automatic Compact (Hertz, 3 days, drop at FCO) · ~1h 30m"
      }
    ],
    "activities": [
      {
        "id": "pienza",
        "name": "Pienza",
        "location": {
          "name": "Pienza",
          "coords": [
            43.0764,
            11.6801
          ],
          "type": "stay",
          "placeQuery": "Pienza, Siena, Tuscany",
          "photo": "/photos/pienza.jpg"
        },
        "category": "attraction",
        "emoji": "🗺️",
        "date": "Jul 27",
        "notes": "Renaissance hilltop town, 15 min from Lupaia"
      }
    ],
    "notes": [
      "Leave from Lake Maggiore to Tuscany. Lupaia Dinner Reservation at 8:30 (booked)",
      "Eat Breakfast at the hotel. Pool. Go to Montelpuciano for the day. Visit the city and go to wineries that are tagged on Google maps. Reservation at Risotrante 4 venti (booked at 8 pm)",
      "Winery. Go to Montalcino for the day with saved Google Map wineries."
    ]
  },
  {
    "date": "July 29 – Aug 1",
    "dateShort": "Jul 29 – Aug 1",
    "location": "Puglia",
    "emoji": "🫒",
    "stay": {
      "id": "puglia",
      "name": "Masseria le Carrube",
      "location": {
        "name": "Masseria le Carrube",
        "coords": [
          40.7285,
          17.5888
        ],
        "type": "stay",
        "placeQuery": "Masseria Le Carrube, Ostuni"
      },
      "checkIn": "Jul 29",
      "checkOut": "Aug 2",
      "nights": 4,
      "description": "Whitewashed masseria estate near the white city of Ostuni.",
      "category": "masseria",
      "emoji": "🫒"
    },
    "legs": [
      {
        "id": "leg6",
        "from": {
          "name": "Rome Fiumicino",
          "coords": [
            41.7999,
            12.2462
          ],
          "type": "airport",
          "placeQuery": "Leonardo da Vinci–Fiumicino Airport",
          "photo": "/photos/FCO.jpg"
        },
        "to": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyła Airport",
          "photo": "/photos/BRI.jpg"
        },
        "mode": "flight",
        "date": "Jul 29",
        "status": "booked",
        "departureTime": "15:15",
        "arrivalTime": "16:20",
        "confirmation": "Z24DST",
        "carrier": "ITA Airways",
        "flightNumber": "AZ1607",
        "price": "EUR 174.10 for 2",
        "notes": "Nonstop Economy · Bags: 1 checked (23kg, booked) + carry-on (8kg) + personal item pp · 1h 05m"
      },
      {
        "id": "leg7",
        "from": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyła Airport",
          "photo": "/photos/BRI.jpg"
        },
        "to": {
          "name": "Ostuni, Puglia",
          "coords": [
            40.7285,
            17.5888
          ],
          "type": "stay",
          "placeQuery": "Ostuni, Puglia, Italy",
          "photo": "/photos/OSTUNI.jpg"
        },
        "mode": "car",
        "date": "Jul 29",
        "status": "booked",
        "departureTime": "4:30",
        "arrivalTime": "9:00+1",
        "confirmation": "Auto Europe US645058086",
        "carrier": "Rental Car",
        "price": "$220",
        "notes": "Fiat 600 or similar, Automatic Compact (Auto Europe, 4 days, drop at BRI) · 4 days"
      }
    ],
    "activities": [
      {
        "id": "ostuni-town",
        "name": "Ostuni Old Town",
        "location": {
          "name": "Ostuni Old Town",
          "coords": [
            40.7317,
            17.5851
          ],
          "type": "stay",
          "placeQuery": "Ostuni, Puglia, Italy",
          "photo": "/photos/ostuni-town.jpg"
        },
        "category": "attraction",
        "emoji": "🕌",
        "date": "Jul 30",
        "notes": "The white city — stunning at sunset"
      }
    ],
    "notes": [
      "Winery",
      "Lupaia to Rome Train (56 min ) or Drive (1 hr 37 min). Fly to Bari ( ~38 dollars)",
      "Borgo Egnazia Beach Club? Go to Ostuni and walk around. Borgo Antico Bistrot( sunset drinks at 6:30, no reservations) Dinner at Oster Del tempo at 9 pm (emailed not confirmed)",
      "Alberobello",
      "Chill day drive around"
    ]
  },
  {
    "date": "August 2–3",
    "dateShort": "Aug 2–3",
    "location": "Oliena",
    "emoji": "🏔️",
    "stay": {
      "id": "su-gologone",
      "name": "Su Gologone Experience Hotel",
      "location": {
        "name": "Su Gologone Experience Hotel",
        "coords": [
          40.2728,
          9.4512
        ],
        "type": "stay",
        "placeQuery": "Art-filled experience hotel at the foot of the Supramonte, near Oliena. Anniversary stay."
      },
      "checkIn": "Aug 2",
      "checkOut": "Aug 4",
      "nights": 2,
      "description": "",
      "category": "hotel",
      "emoji": "🏔️"
    },
    "legs": [
      {
        "id": "leg8",
        "from": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyła Airport",
          "photo": "/photos/BRI.jpg"
        },
        "to": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport"
        },
        "mode": "flight",
        "date": "Aug 2",
        "status": "booked",
        "departureTime": "8:15",
        "arrivalTime": "9:45",
        "confirmation": "TSCHHB",
        "carrier": "Ryanair",
        "flightNumber": "FR8726",
        "price": "Euro 278 for 2",
        "notes": "Nonstop Economy · Bags: 2×20kg checked (booked) + 1 under-seat bag 40×20×25cm pp; no cabin bag · 1h 30m"
      },
      {
        "id": "leg9",
        "from": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport"
        },
        "to": {
          "name": "Sardinia",
          "coords": [
            39.2238,
            9.1217
          ],
          "type": "stay",
          "placeQuery": "Sardinia, Italy"
        },
        "mode": "car",
        "date": "Aug 2",
        "status": "booked",
        "departureTime": "10:00",
        "arrivalTime": "10:00+1",
        "confirmation": "Auto Europe US228145669 / Avis 20221246US3",
        "carrier": "Rental Car",
        "price": "$330",
        "notes": "Nissan Juke or similar, Automatic Compact (Avis via Auto Europe, 4 days, drop at CAG) · 4 days"
      }
    ],
    "activities": [],
    "notes": [
      "le Carrube → fly BRI–CAG 8:15, pick up rental at Cagliari, drive to Oliena. Check in Su Gologone — Junior Suite, 2 nights. Anniversary stay 🎉"
    ]
  },
  {
    "date": "August 4–5",
    "dateShort": "Aug 4–5",
    "location": "Castiadas",
    "emoji": "🏖️",
    "stay": {
      "id": "spiagge-san-pietro",
      "name": "Spiagge San Pietro",
      "location": {
        "name": "Spiagge San Pietro",
        "coords": [
          39.2789,
          9.5936
        ],
        "type": "stay",
        "placeQuery": "Relaxed beach resort on the southeast coast at Castiadas, near Costa Rei."
      },
      "checkIn": "Aug 4",
      "checkOut": "Aug 6",
      "nights": 2,
      "description": "",
      "category": "resort",
      "emoji": "🏖️"
    },
    "legs": [],
    "activities": [],
    "notes": [
      "Drive to the SE coast. Check in Spiagge San Pietro, Castiadas — Deluxe Double, 2 nights. Beach days + Costa Rei."
    ]
  },
  {
    "date": "August 6",
    "dateShort": "Aug 6",
    "location": "Home",
    "emoji": "🏠",
    "legs": [
      {
        "id": "leg10",
        "from": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport"
        },
        "to": {
          "name": "Paris CDG",
          "coords": [
            49.0097,
            2.5479
          ],
          "type": "airport",
          "placeQuery": "Paris Charles de Gaulle Airport"
        },
        "mode": "flight",
        "date": "Aug 6",
        "status": "booked",
        "departureTime": "12:30",
        "arrivalTime": "14:45",
        "confirmation": "XDQETZ",
        "carrier": "Air France",
        "flightNumber": "AF1111",
        "price": "120,000 miles + $882.46",
        "notes": "Business · Bags: 2 checked (32kg) + carry-on pp · 2h 15m"
      },
      {
        "id": "leg11",
        "from": {
          "name": "Paris CDG",
          "coords": [
            49.0097,
            2.5479
          ],
          "type": "airport",
          "placeQuery": "Paris Charles de Gaulle Airport"
        },
        "to": {
          "name": "New York JFK",
          "coords": [
            40.6413,
            -73.7781
          ],
          "type": "airport",
          "placeQuery": "John F. Kennedy International Airport, Queens, New York",
          "photo": "/photos/JFK.jpg"
        },
        "mode": "flight",
        "date": "Aug 6",
        "status": "booked",
        "departureTime": "20:30",
        "arrivalTime": "22:40",
        "confirmation": "XDQETZ",
        "carrier": "Air France",
        "flightNumber": "AF0012",
        "price": "see leg above",
        "notes": "8h 10m"
      }
    ],
    "activities": []
  }
] as unknown as TimelineDay[];
