// ⚠ AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Source of truth: the Google Sheet. Run `npm run sync` to regenerate.
import type { Stay, Leg, Activity, TimelineDay } from "./trip";

export const stays = [
  {
    "id": "lake-maggiore",
    "name": "Regina Palace Hotel",
    "location": {
      "name": "Regina Palace Hotel",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Stresa Lake Maggiore Italy"
    },
    "checkIn": "Jul 23",
    "checkOut": "Jul 26",
    "nights": 3,
    "description": "Grand lakeside hotel in Stresa for a friend's wedding celebration.",
    "category": "hotel",
    "emoji": "🏛️"
  },
  {
    "id": "tuscany",
    "name": "Lupaia Hotel",
    "location": {
      "name": "Lupaia Hotel",
      "coords": [
        43.0667,
        11.7167
      ],
      "type": "stay",
      "placeQuery": "Lupaia Hotel Monticchiello Tuscany"
    },
    "checkIn": "Jul 26",
    "checkOut": "Jul 29",
    "nights": 3,
    "description": "Hilltop boutique hotel near Monticchiello in the Val d'Orcia.",
    "category": "villa",
    "emoji": "🌿"
  },
  {
    "id": "puglia",
    "name": "Masseria le Carrube",
    "location": {
      "name": "Masseria le Carrube",
      "coords": [
        40.7285,
        17.5888
      ],
      "type": "stay",
      "placeQuery": "Ostuni Puglia Italy white city"
    },
    "checkIn": "Jul 29",
    "checkOut": "Aug 2",
    "nights": 4,
    "description": "Whitewashed masseria estate near the white city of Ostuni.",
    "category": "masseria",
    "emoji": "🫒"
  },
  {
    "id": "sardinia",
    "name": "Sardinia (TBD)",
    "location": {
      "name": "Sardinia (TBD)",
      "coords": [
        39.2238,
        9.1217
      ],
      "type": "stay",
      "placeQuery": "Cagliari Sardinia Italy"
    },
    "checkIn": "Aug 2",
    "checkOut": "Aug 6",
    "nights": 4,
    "description": "Four nights in Sardinia before the flight home from Cagliari.",
    "category": "villa",
    "emoji": "🏖️"
  }
] as unknown as Stay[];

export const legs = [
  {
    "id": "leg1",
    "from": {
      "name": "New York JFK",
      "coords": [
        40.6413,
        -73.7781
      ],
      "type": "airport",
      "placeQuery": "JFK Airport New York"
    },
    "to": {
      "name": "Milan Malpensa",
      "coords": [
        45.6306,
        8.7281
      ],
      "type": "airport",
      "placeQuery": "Milan Malpensa Airport"
    },
    "mode": "flight",
    "date": "Jul 22",
    "status": "pending",
    "departureTime": "21:55",
    "arrivalTime": "12:05+1",
    "carrier": "Delta",
    "flightNumber": "DL184",
    "price": "$957 for 2",
    "notes": "Nonstop Economy · 8h 10m"
  },
  {
    "id": "leg2",
    "from": {
      "name": "Milan Malpensa",
      "coords": [
        45.6306,
        8.7281
      ],
      "type": "airport",
      "placeQuery": "Milan Malpensa Airport"
    },
    "to": {
      "name": "Stresa, Lake Maggiore",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Stresa Lake Maggiore Italy"
    },
    "mode": "train",
    "date": "Jul 23",
    "status": "pending",
    "departureTime": "afternoon",
    "price": "~$34 for 2",
    "notes": "Trenord regional (1 connection, 1h15-1h50) · ~1h 30m"
  },
  {
    "id": "leg3",
    "from": {
      "name": "Stresa, Lake Maggiore",
      "coords": [
        45.8832,
        8.5355
      ],
      "type": "stay",
      "placeQuery": "Stresa Lake Maggiore Italy"
    },
    "to": {
      "name": "Milano Centrale",
      "coords": [
        45.4851,
        9.2035
      ],
      "type": "station",
      "placeQuery": "Milano Centrale Station"
    },
    "mode": "train",
    "date": "Jul 26",
    "status": "pending",
    "departureTime": "morning",
    "price": "~$34 for 2",
    "notes": "Trenord regional (1 connection) · ~1h 30m"
  },
  {
    "id": "leg4",
    "from": {
      "name": "Milano Centrale",
      "coords": [
        45.4851,
        9.2035
      ],
      "type": "station",
      "placeQuery": "Milano Centrale Station"
    },
    "to": {
      "name": "Firenze SMN",
      "coords": [
        43.776,
        11.2457
      ],
      "type": "station",
      "placeQuery": "Santa Maria Novella Florence"
    },
    "mode": "train",
    "date": "Jul 26",
    "status": "booked",
    "departureTime": "11:40",
    "arrivalTime": "13:35",
    "confirmation": "CCDUHP",
    "carrier": "Italo",
    "flightNumber": "Train 9931",
    "price": "$155.58 for 2 (Dhrumi Amex)",
    "notes": "Prima Business Flex · 1h 55m"
  },
  {
    "id": "leg5",
    "from": {
      "name": "Firenze SMN",
      "coords": [
        43.776,
        11.2457
      ],
      "type": "station",
      "placeQuery": "Santa Maria Novella Florence"
    },
    "to": {
      "name": "Lupaia, Tuscany",
      "coords": [
        43.0667,
        11.7167
      ],
      "type": "stay",
      "placeQuery": "Lupaia Hotel Monticchiello Tuscany"
    },
    "mode": "car",
    "date": "Jul 26",
    "status": "booked",
    "confirmation": "Hertz L64746533C6 / AE Voucher 359733840",
    "carrier": "Rental Car",
    "price": "$389.63 (Dhrumi Amex)",
    "notes": "Jeep Avenger or similar, Automatic Compact (Hertz, 3 days, drop at FCO) · ~1h 30m"
  },
  {
    "id": "leg6",
    "from": {
      "name": "Rome Fiumicino",
      "coords": [
        41.7999,
        12.2462
      ],
      "type": "airport",
      "placeQuery": "Rome Fiumicino Airport FCO"
    },
    "to": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyla Airport"
    },
    "mode": "flight",
    "date": "Jul 29",
    "status": "booked",
    "departureTime": "15:15",
    "arrivalTime": "16:20",
    "confirmation": "Z24DST",
    "carrier": "ITA Airways",
    "flightNumber": "AZ1607",
    "price": "EUR 174.10 for 2",
    "notes": "Nonstop Economy · 1h 05m"
  },
  {
    "id": "leg7",
    "from": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyla Airport"
    },
    "to": {
      "name": "Ostuni, Puglia",
      "coords": [
        40.7285,
        17.5888
      ],
      "type": "stay",
      "placeQuery": "Ostuni Puglia Italy white city"
    },
    "mode": "car",
    "date": "Jul 29",
    "status": "pending",
    "carrier": "Rental Car",
    "price": "$150",
    "notes": "Compact Automatic (4 days, drop at BRI) · 4 days"
  },
  {
    "id": "leg8",
    "from": {
      "name": "Bari Airport",
      "coords": [
        41.1387,
        16.7624
      ],
      "type": "airport",
      "placeQuery": "Bari Karol Wojtyla Airport"
    },
    "to": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport Sardinia"
    },
    "mode": "flight",
    "date": "Aug 2",
    "status": "booked",
    "departureTime": "8:15",
    "arrivalTime": "9:45",
    "confirmation": "TSCHHB",
    "carrier": "Ryanair",
    "price": "Euro 278 for 2",
    "notes": "Nonstop Economy · 1h 30m"
  },
  {
    "id": "leg9",
    "from": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport Sardinia"
    },
    "to": {
      "name": "Sardinia",
      "coords": [
        39.2238,
        9.1217
      ],
      "type": "stay",
      "placeQuery": "Cagliari Sardinia Italy"
    },
    "mode": "car",
    "date": "Aug 2",
    "status": "pending",
    "carrier": "Rental Car",
    "price": "$181",
    "notes": "Opel Mokka Compact SUV Auto (4 days, drop at CAG) · 4 days"
  },
  {
    "id": "leg10",
    "from": {
      "name": "Cagliari Airport",
      "coords": [
        39.2548,
        9.054
      ],
      "type": "airport",
      "placeQuery": "Cagliari Elmas Airport Sardinia"
    },
    "to": {
      "name": "Paris CDG",
      "coords": [
        49.0097,
        2.5479
      ],
      "type": "airport",
      "placeQuery": "Charles de Gaulle Airport Paris"
    },
    "mode": "flight",
    "date": "Aug 6",
    "status": "booked",
    "departureTime": "12:30",
    "arrivalTime": "14:45",
    "confirmation": "XDQETZ",
    "carrier": "Air France",
    "flightNumber": "AF1111",
    "price": "120,000 miles + $882.46",
    "notes": "2h 15m"
  },
  {
    "id": "leg11",
    "from": {
      "name": "Paris CDG",
      "coords": [
        49.0097,
        2.5479
      ],
      "type": "airport",
      "placeQuery": "Charles de Gaulle Airport Paris"
    },
    "to": {
      "name": "New York JFK",
      "coords": [
        40.6413,
        -73.7781
      ],
      "type": "airport",
      "placeQuery": "JFK Airport New York"
    },
    "mode": "flight",
    "date": "Aug 6",
    "status": "booked",
    "departureTime": "20:30",
    "arrivalTime": "22:40",
    "confirmation": "XDQETZ",
    "carrier": "Air France",
    "flightNumber": "AF0012",
    "price": "see leg above",
    "notes": "8h 10m"
  }
] as unknown as Leg[];

export const activities = [
  {
    "id": "borromean",
    "name": "Borromean Islands",
    "location": {
      "name": "Borromean Islands",
      "coords": [
        45.8992,
        8.5108
      ],
      "type": "stay",
      "placeQuery": "Isola Bella Borromean Islands"
    },
    "category": "attraction",
    "emoji": "🏝️",
    "date": "Jul 23–25",
    "notes": "Baroque palace gardens on the lake"
  },
  {
    "id": "pienza",
    "name": "Pienza",
    "location": {
      "name": "Pienza",
      "coords": [
        43.0764,
        11.6801
      ],
      "type": "stay",
      "placeQuery": "Pienza Tuscany Italy"
    },
    "category": "attraction",
    "emoji": "🗺️",
    "date": "Jul 27",
    "notes": "Renaissance hilltop town, 15 min from Lupaia"
  },
  {
    "id": "ostuni-town",
    "name": "Ostuni Old Town",
    "location": {
      "name": "Ostuni Old Town",
      "coords": [
        40.7317,
        17.5851
      ],
      "type": "stay",
      "placeQuery": "Ostuni white city old town Puglia"
    },
    "category": "attraction",
    "emoji": "🕌",
    "date": "Jul 30",
    "notes": "The white city — stunning at sunset"
  }
] as unknown as Activity[];

export const timeline = [
  {
    "date": "July 22",
    "dateShort": "Jul 22",
    "location": "Milan",
    "emoji": "✈️",
    "legs": [
      {
        "id": "leg1",
        "from": {
          "name": "New York JFK",
          "coords": [
            40.6413,
            -73.7781
          ],
          "type": "airport",
          "placeQuery": "JFK Airport New York"
        },
        "to": {
          "name": "Milan Malpensa",
          "coords": [
            45.6306,
            8.7281
          ],
          "type": "airport",
          "placeQuery": "Milan Malpensa Airport"
        },
        "mode": "flight",
        "date": "Jul 22",
        "status": "pending",
        "departureTime": "21:55",
        "arrivalTime": "12:05+1",
        "carrier": "Delta",
        "flightNumber": "DL184",
        "price": "$957 for 2",
        "notes": "Nonstop Economy · 8h 10m"
      }
    ],
    "activities": [],
    "notes": [
      "Depart from NYC"
    ]
  },
  {
    "date": "July 23–25",
    "dateShort": "Jul 23–25",
    "location": "Lake Maggiore",
    "emoji": "🏛️",
    "stay": {
      "id": "lake-maggiore",
      "name": "Regina Palace Hotel",
      "location": {
        "name": "Regina Palace Hotel",
        "coords": [
          45.8832,
          8.5355
        ],
        "type": "stay",
        "placeQuery": "Stresa Lake Maggiore Italy"
      },
      "checkIn": "Jul 23",
      "checkOut": "Jul 26",
      "nights": 3,
      "description": "Grand lakeside hotel in Stresa for a friend's wedding celebration.",
      "category": "hotel",
      "emoji": "🏛️"
    },
    "legs": [
      {
        "id": "leg2",
        "from": {
          "name": "Milan Malpensa",
          "coords": [
            45.6306,
            8.7281
          ],
          "type": "airport",
          "placeQuery": "Milan Malpensa Airport"
        },
        "to": {
          "name": "Stresa, Lake Maggiore",
          "coords": [
            45.8832,
            8.5355
          ],
          "type": "stay",
          "placeQuery": "Stresa Lake Maggiore Italy"
        },
        "mode": "train",
        "date": "Jul 23",
        "status": "pending",
        "departureTime": "afternoon",
        "price": "~$34 for 2",
        "notes": "Trenord regional (1 connection, 1h15-1h50) · ~1h 30m"
      }
    ],
    "activities": [
      {
        "id": "borromean",
        "name": "Borromean Islands",
        "location": {
          "name": "Borromean Islands",
          "coords": [
            45.8992,
            8.5108
          ],
          "type": "stay",
          "placeQuery": "Isola Bella Borromean Islands"
        },
        "category": "attraction",
        "emoji": "🏝️",
        "date": "Jul 23–25",
        "notes": "Baroque palace gardens on the lake"
      }
    ],
    "notes": [
      "Welcome Party 6pm-11pm at Sky Bar at Hotel La Palma",
      "Haldi 10 am-2pm Sangeet 6:30pm-11:30pm at 3 Viale Siemens",
      "Baraat and Milni Reception Grand Hotel Des Iles Borromees"
    ]
  },
  {
    "date": "July 26–28",
    "dateShort": "Jul 26–28",
    "location": "Tuscany",
    "emoji": "🌿",
    "stay": {
      "id": "tuscany",
      "name": "Lupaia Hotel",
      "location": {
        "name": "Lupaia Hotel",
        "coords": [
          43.0667,
          11.7167
        ],
        "type": "stay",
        "placeQuery": "Lupaia Hotel Monticchiello Tuscany"
      },
      "checkIn": "Jul 26",
      "checkOut": "Jul 29",
      "nights": 3,
      "description": "Hilltop boutique hotel near Monticchiello in the Val d'Orcia.",
      "category": "villa",
      "emoji": "🌿"
    },
    "legs": [
      {
        "id": "leg3",
        "from": {
          "name": "Stresa, Lake Maggiore",
          "coords": [
            45.8832,
            8.5355
          ],
          "type": "stay",
          "placeQuery": "Stresa Lake Maggiore Italy"
        },
        "to": {
          "name": "Milano Centrale",
          "coords": [
            45.4851,
            9.2035
          ],
          "type": "station",
          "placeQuery": "Milano Centrale Station"
        },
        "mode": "train",
        "date": "Jul 26",
        "status": "pending",
        "departureTime": "morning",
        "price": "~$34 for 2",
        "notes": "Trenord regional (1 connection) · ~1h 30m"
      },
      {
        "id": "leg4",
        "from": {
          "name": "Milano Centrale",
          "coords": [
            45.4851,
            9.2035
          ],
          "type": "station",
          "placeQuery": "Milano Centrale Station"
        },
        "to": {
          "name": "Firenze SMN",
          "coords": [
            43.776,
            11.2457
          ],
          "type": "station",
          "placeQuery": "Santa Maria Novella Florence"
        },
        "mode": "train",
        "date": "Jul 26",
        "status": "booked",
        "departureTime": "11:40",
        "arrivalTime": "13:35",
        "confirmation": "CCDUHP",
        "carrier": "Italo",
        "flightNumber": "Train 9931",
        "price": "$155.58 for 2 (Dhrumi Amex)",
        "notes": "Prima Business Flex · 1h 55m"
      },
      {
        "id": "leg5",
        "from": {
          "name": "Firenze SMN",
          "coords": [
            43.776,
            11.2457
          ],
          "type": "station",
          "placeQuery": "Santa Maria Novella Florence"
        },
        "to": {
          "name": "Lupaia, Tuscany",
          "coords": [
            43.0667,
            11.7167
          ],
          "type": "stay",
          "placeQuery": "Lupaia Hotel Monticchiello Tuscany"
        },
        "mode": "car",
        "date": "Jul 26",
        "status": "booked",
        "confirmation": "Hertz L64746533C6 / AE Voucher 359733840",
        "carrier": "Rental Car",
        "price": "$389.63 (Dhrumi Amex)",
        "notes": "Jeep Avenger or similar, Automatic Compact (Hertz, 3 days, drop at FCO) · ~1h 30m"
      }
    ],
    "activities": [
      {
        "id": "pienza",
        "name": "Pienza",
        "location": {
          "name": "Pienza",
          "coords": [
            43.0764,
            11.6801
          ],
          "type": "stay",
          "placeQuery": "Pienza Tuscany Italy"
        },
        "category": "attraction",
        "emoji": "🗺️",
        "date": "Jul 27",
        "notes": "Renaissance hilltop town, 15 min from Lupaia"
      }
    ],
    "notes": [
      "Leave from Lake Maggiore to Tuscany",
      "Winery",
      "Winery"
    ]
  },
  {
    "date": "July 29 – Aug 1",
    "dateShort": "Jul 29 – Aug 1",
    "location": "Puglia",
    "emoji": "🫒",
    "stay": {
      "id": "puglia",
      "name": "Masseria le Carrube",
      "location": {
        "name": "Masseria le Carrube",
        "coords": [
          40.7285,
          17.5888
        ],
        "type": "stay",
        "placeQuery": "Ostuni Puglia Italy white city"
      },
      "checkIn": "Jul 29",
      "checkOut": "Aug 2",
      "nights": 4,
      "description": "Whitewashed masseria estate near the white city of Ostuni.",
      "category": "masseria",
      "emoji": "🫒"
    },
    "legs": [
      {
        "id": "leg6",
        "from": {
          "name": "Rome Fiumicino",
          "coords": [
            41.7999,
            12.2462
          ],
          "type": "airport",
          "placeQuery": "Rome Fiumicino Airport FCO"
        },
        "to": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyla Airport"
        },
        "mode": "flight",
        "date": "Jul 29",
        "status": "booked",
        "departureTime": "15:15",
        "arrivalTime": "16:20",
        "confirmation": "Z24DST",
        "carrier": "ITA Airways",
        "flightNumber": "AZ1607",
        "price": "EUR 174.10 for 2",
        "notes": "Nonstop Economy · 1h 05m"
      },
      {
        "id": "leg7",
        "from": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyla Airport"
        },
        "to": {
          "name": "Ostuni, Puglia",
          "coords": [
            40.7285,
            17.5888
          ],
          "type": "stay",
          "placeQuery": "Ostuni Puglia Italy white city"
        },
        "mode": "car",
        "date": "Jul 29",
        "status": "pending",
        "carrier": "Rental Car",
        "price": "$150",
        "notes": "Compact Automatic (4 days, drop at BRI) · 4 days"
      }
    ],
    "activities": [
      {
        "id": "ostuni-town",
        "name": "Ostuni Old Town",
        "location": {
          "name": "Ostuni Old Town",
          "coords": [
            40.7317,
            17.5851
          ],
          "type": "stay",
          "placeQuery": "Ostuni white city old town Puglia"
        },
        "category": "attraction",
        "emoji": "🕌",
        "date": "Jul 30",
        "notes": "The white city — stunning at sunset"
      }
    ],
    "notes": [
      "Winery",
      "Lupaia to Rome Train (56 min ) or Drive (1 hr 37 min). Fly to Bari ( ~38 dollars)",
      "Borgo antico bistrot at sunset. No reservations. Get there at 6:30",
      "Oster del tempo Resturant at 7 pm. Reached out to both confirmed."
    ]
  },
  {
    "date": "August 2–5",
    "dateShort": "Aug 2–5",
    "location": "Sardinia",
    "emoji": "🏖️",
    "stay": {
      "id": "sardinia",
      "name": "Sardinia (TBD)",
      "location": {
        "name": "Sardinia (TBD)",
        "coords": [
          39.2238,
          9.1217
        ],
        "type": "stay",
        "placeQuery": "Cagliari Sardinia Italy"
      },
      "checkIn": "Aug 2",
      "checkOut": "Aug 6",
      "nights": 4,
      "description": "Four nights in Sardinia before the flight home from Cagliari.",
      "category": "villa",
      "emoji": "🏖️"
    },
    "legs": [
      {
        "id": "leg8",
        "from": {
          "name": "Bari Airport",
          "coords": [
            41.1387,
            16.7624
          ],
          "type": "airport",
          "placeQuery": "Bari Karol Wojtyla Airport"
        },
        "to": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport Sardinia"
        },
        "mode": "flight",
        "date": "Aug 2",
        "status": "booked",
        "departureTime": "8:15",
        "arrivalTime": "9:45",
        "confirmation": "TSCHHB",
        "carrier": "Ryanair",
        "price": "Euro 278 for 2",
        "notes": "Nonstop Economy · 1h 30m"
      },
      {
        "id": "leg9",
        "from": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport Sardinia"
        },
        "to": {
          "name": "Sardinia",
          "coords": [
            39.2238,
            9.1217
          ],
          "type": "stay",
          "placeQuery": "Cagliari Sardinia Italy"
        },
        "mode": "car",
        "date": "Aug 2",
        "status": "pending",
        "carrier": "Rental Car",
        "price": "$181",
        "notes": "Opel Mokka Compact SUV Auto (4 days, drop at CAG) · 4 days"
      }
    ],
    "activities": []
  },
  {
    "date": "August 6",
    "dateShort": "Aug 6",
    "location": "Home",
    "emoji": "🏠",
    "legs": [
      {
        "id": "leg10",
        "from": {
          "name": "Cagliari Airport",
          "coords": [
            39.2548,
            9.054
          ],
          "type": "airport",
          "placeQuery": "Cagliari Elmas Airport Sardinia"
        },
        "to": {
          "name": "Paris CDG",
          "coords": [
            49.0097,
            2.5479
          ],
          "type": "airport",
          "placeQuery": "Charles de Gaulle Airport Paris"
        },
        "mode": "flight",
        "date": "Aug 6",
        "status": "booked",
        "departureTime": "12:30",
        "arrivalTime": "14:45",
        "confirmation": "XDQETZ",
        "carrier": "Air France",
        "flightNumber": "AF1111",
        "price": "120,000 miles + $882.46",
        "notes": "2h 15m"
      },
      {
        "id": "leg11",
        "from": {
          "name": "Paris CDG",
          "coords": [
            49.0097,
            2.5479
          ],
          "type": "airport",
          "placeQuery": "Charles de Gaulle Airport Paris"
        },
        "to": {
          "name": "New York JFK",
          "coords": [
            40.6413,
            -73.7781
          ],
          "type": "airport",
          "placeQuery": "JFK Airport New York"
        },
        "mode": "flight",
        "date": "Aug 6",
        "status": "booked",
        "departureTime": "20:30",
        "arrivalTime": "22:40",
        "confirmation": "XDQETZ",
        "carrier": "Air France",
        "flightNumber": "AF0012",
        "price": "see leg above",
        "notes": "8h 10m"
      }
    ],
    "activities": []
  }
] as unknown as TimelineDay[];
